spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/postgres}
    username: postgres
    password: postgres
server:
  port: 8082
  shutdown: GRACEFUL

management:
  endpoints:
    web:
      exposure:
        include: *

