name: catalog-service
on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build code
        working-directory: ${{env.working-directory}}
        run: ./mnvw clean install